-- D1 schema for congress-one.
-- Each row is a single bill whose plain-English and Chinese summaries
-- have already been generated by Gemini and cached here.
--
-- `bill_id` is a deterministic key of the form "<congress>-<type>-<number>",
-- e.g. "119-hr-1234".
CREATE TABLE IF NOT EXISTS bills (
    bill_id             TEXT PRIMARY KEY,
    congress            INTEGER NOT NULL,
    bill_type           TEXT NOT NULL,
    bill_number         INTEGER NOT NULL,
    title               TEXT NOT NULL,
    sponsor             TEXT,
    introduced_date     TEXT NOT NULL,          -- ISO 8601 (YYYY-MM-DD)
    latest_action_date  TEXT,
    latest_action_text  TEXT,
    source_url          TEXT NOT NULL,
    -- Cached LLM output.
    summary_en          TEXT NOT NULL,
    summary_zh          TEXT NOT NULL,
    -- Bookkeeping.
    summarized_at       TEXT NOT NULL,
    model               TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bills_introduced_date
    ON bills (introduced_date DESC);

CREATE INDEX IF NOT EXISTS idx_bills_latest_action_date
    ON bills (latest_action_date DESC);
