// Server-rendered HTML. Kept deliberately minimal — no framework, no build step.

import type { BillRow } from "./types";

export function renderLayout(title: string, body: string): string {
    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
         max-width: 860px; margin: 0 auto; padding: 1.5rem 1rem 4rem; line-height: 1.55; }
  h1 { margin: 0 0 .25rem; font-size: 1.6rem; }
  .tagline { color: #666; margin: 0 0 1.5rem; }
  form.controls { display: flex; flex-wrap: wrap; gap: .5rem; margin-bottom: 1.25rem; }
  form.controls input[type=text], form.controls select {
    padding: .45rem .6rem; border: 1px solid #ccc; border-radius: 6px; font-size: .95rem;
    background: transparent; color: inherit;
  }
  form.controls button { padding: .45rem .9rem; border: 1px solid #888; border-radius: 6px;
    background: transparent; color: inherit; cursor: pointer; font-size: .95rem; }
  article.bill { border: 1px solid #ddd3; border-radius: 10px; padding: 1rem 1.1rem;
    margin-bottom: 1rem; background: #fff1; }
  article.bill h2 { margin: 0 0 .25rem; font-size: 1.15rem; }
  article.bill h2 a { color: inherit; text-decoration: none; }
  article.bill h2 a:hover { text-decoration: underline; }
  .meta { color: #888; font-size: .85rem; margin-bottom: .65rem; }
  .tabs { display: flex; gap: .25rem; margin: .4rem 0 .6rem; }
  .tabs button { padding: .25rem .7rem; border: 1px solid #8886; border-radius: 999px;
    background: transparent; color: inherit; cursor: pointer; font-size: .8rem; }
  .tabs button[aria-selected=true] { background: #8882; font-weight: 600; }
  .summary { white-space: pre-wrap; font-size: .95rem; }
  .summary.zh { display: none; font-family: "Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif; }
  article.bill[data-lang=zh] .summary.en { display: none; }
  article.bill[data-lang=zh] .summary.zh { display: block; }
  .empty { color: #888; text-align: center; padding: 3rem 1rem; }
  footer { color: #888; font-size: .8rem; margin-top: 3rem; text-align: center; }
  footer a { color: inherit; }
</style>
</head>
<body>
${body}
<script>
  // Per-card language toggle.
  document.addEventListener("click", (e) => {
    const btn = e.target.closest(".tabs button");
    if (!btn) return;
    const card = btn.closest("article.bill");
    if (!card) return;
    const lang = btn.dataset.lang;
    card.dataset.lang = lang;
    card.querySelectorAll(".tabs button").forEach((b) => {
      b.setAttribute("aria-selected", b.dataset.lang === lang ? "true" : "false");
    });
  });
</script>
</body>
</html>`;
}

export function renderIndex(opts: {
    bills: BillRow[];
    sortBy: "introduced_date" | "latest_action_date";
    order: "desc" | "asc";
    q: string;
    total: number;
}): string {
    const { bills, sortBy, order, q, total } = opts;

    const cards = bills.length
        ? bills.map(renderBillCard).join("\n")
        : `<div class="empty">No bills cached yet. The weekly pipeline will populate this page, or an admin can trigger <code>/admin/ingest</code>.</div>`;

    const body = `
<h1>Congress One</h1>
<p class="tagline">Plain-English &amp; 简体中文 summaries of recent U.S. Congress bills. Cached, non-partisan, one screen each.</p>

<form class="controls" method="get" action="/">
  <input type="text" name="q" placeholder="Search title…" value="${esc(q)}">
  <select name="sort">
    <option value="introduced_date" ${sortBy === "introduced_date" ? "selected" : ""}>Sort: Introduced date</option>
    <option value="latest_action_date" ${sortBy === "latest_action_date" ? "selected" : ""}>Sort: Latest action</option>
  </select>
  <select name="order">
    <option value="desc" ${order === "desc" ? "selected" : ""}>Newest first</option>
    <option value="asc" ${order === "asc" ? "selected" : ""}>Oldest first</option>
  </select>
  <button type="submit">Apply</button>
</form>

<p class="meta">${bills.length} shown · ${total} total cached</p>

${cards}

<footer>
  Source: <a href="https://api.congress.gov/">api.congress.gov</a> · Summaries generated by
  Anthropic Claude and cached in Cloudflare D1 · <a href="/api/bills">JSON feed</a>
</footer>
`;

    return renderLayout("Congress One — plain-language bill summaries", body);
}

function renderBillCard(b: BillRow): string {
    const label = formatLabel(b);
    const action = b.latest_action_text
        ? `${esc(b.latest_action_date ?? "")} · ${esc(truncate(b.latest_action_text, 140))}`
        : "No recorded action yet";
    return `<article class="bill" data-lang="en">
  <h2><a href="${esc(b.source_url)}" target="_blank" rel="noopener">${esc(label)}: ${esc(b.title)}</a></h2>
  <div class="meta">
    Introduced ${esc(b.introduced_date)}${b.sponsor ? " · Sponsor: " + esc(b.sponsor) : ""}
    <br>Latest action: ${action}
  </div>
  <div class="tabs" role="tablist">
    <button data-lang="en" aria-selected="true">English</button>
    <button data-lang="zh" aria-selected="false">中文</button>
  </div>
  <div class="summary en">${esc(b.summary_en)}</div>
  <div class="summary zh">${esc(b.summary_zh)}</div>
</article>`;
}

function formatLabel(b: BillRow): string {
    const t = b.bill_type.toUpperCase();
    const pretty = ({
        HR: "H.R.",
        S: "S.",
        HJRES: "H.J.Res.",
        SJRES: "S.J.Res.",
        HCONRES: "H.Con.Res.",
        SCONRES: "S.Con.Res.",
        HRES: "H.Res.",
        SRES: "S.Res.",
    } as Record<string, string>)[t] ?? t;
    return `${pretty} ${b.bill_number}`;
}

function truncate(s: string, n: number): string {
    return s.length <= n ? s : s.slice(0, n - 1).trimEnd() + "…";
}

function esc(s: string): string {
    return s
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");
}
